server:
  port: 8081
  servlet:
    context-path: /jollygame

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.141.63.97:3306/mapstruct?useUnicode=true&characterEncoding=utf-8
    username: root
    password: mysql456123z

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置 1.定义dao包的几倍  2.定义日志输出位置  3.配置每天一个日志文件，最大文件数5个
logging:
  level:
    com.apple.firsttest.dao: debug
  file:
    path: /data/log
  logback:
    rollingpolicy:
      file-name-pattern: jollygame-%d{yyyy-MM-dd}.log
      max-history: 5
